import type { MetadataRoute } from "next";

/**
 * PWA manifest.
 * Icons are generated by scripts/generate-icons.mjs and validated by
 * scripts/check-icons.mjs / scripts/check-app-packaging.mjs.
 * Service worker registration is intentionally deferred to avoid stale
 * finance data caches; see docs/app-roadmap.md.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "오른스코어 — 한국 주식 탐색 도구",
    short_name: "오른스코어",
    description: "138개 종목의 자체 지표 4종 · PER · PBR · ROE · DART 공시 신호를 한 화면에서.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    dir: "ltr",
    categories: ["finance"],
    background_color: "#09090b",
    theme_color: "#09090b",
    lang: "ko-KR",
    orientation: "portrait",
    shortcuts: [
      { name: "오늘", short_name: "오늘", url: "/today" },
      { name: "종목 찾기", short_name: "종목", url: "/stocks" },
      { name: "공시 신호", short_name: "공시", url: "/disclosures" },
    ],
    icons: [
      {
        src: "/icon.svg",
        type: "image/svg+xml",
        sizes: "any",
        purpose: "any",
      },
      {
        src: "/icon-192.png",
        type: "image/png",
        sizes: "192x192",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "any",
      },
      {
        src: "/icon-512-maskable.png",
        type: "image/png",
        sizes: "512x512",
        purpose: "maskable",
      },
    ],
  };
}
