// Metrics 2.5.1 TypeScript 계약 생성기 (Slice J) — 실행: node scripts/gen_metrics251_contracts.mjs [--check]
//
// 입력(정본): config/metrics/2.5.1.contract.json  (파이썬이 내보낸 enum·필수키·체크섬 키)
//             config/metrics/2.5.1.projection.schema.json  (공개 후보 projection DTO 구조)
// 출력: scripts/metrics251/contracts.generated.ts  (문자열 리터럴 union + const 배열 + projection DTO + 소스 해시)
//
//   --check: 재생성 결과를 디스크 파일과 바이트 비교. 드리프트면 종료코드 1(쓰지 않음).
//   기본:    파일에 쓴다.
//
// 이 생성기는 계약 "타입"만 만든다 — 점수 산식을 구현하지 않는다(§10 Slice J). 표준 라이브러리만 사용.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join, relative } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const CONTRACT_PATH = join(ROOT, "config", "metrics", "2.5.1.contract.json");
const PROJECTION_SCHEMA_PATH = join(ROOT, "config", "metrics", "2.5.1.projection.schema.json");
const OUT_PATH = join(ROOT, "scripts", "metrics251", "contracts.generated.ts");

function sha256(buf) {
  return createHash("sha256").update(buf).digest("hex");
}

function readBytes(p) {
  return readFileSync(p);
}

// PascalCase 헬퍼(enum 이름 → 타입 이름).
function pascal(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

// JSON Schema(사용하는 부분집합) → TS 타입 문자열. 재귀적. 산식이 아니라 형태만 방출한다.
function tsTypeFromSchema(node) {
  if (node == null || typeof node !== "object") return "unknown";
  if (Object.prototype.hasOwnProperty.call(node, "const")) {
    return JSON.stringify(node.const);
  }
  if (Array.isArray(node.enum)) {
    return node.enum.map((v) => JSON.stringify(v)).join(" | ");
  }
  if (Array.isArray(node.type)) {
    return node.type.map((t) => primType(t)).join(" | ");
  }
  switch (node.type) {
    case "object": {
      const props = node.properties || {};
      const required = new Set(node.required || []);
      const keys = Object.keys(props);
      if (keys.length === 0) return "Record<string, unknown>";
      const fields = keys.map((k) => {
        const opt = required.has(k) ? "" : "?";
        return `${JSON.stringify(k)}${opt}: ${tsTypeFromSchema(props[k])}`;
      });
      return `{ ${fields.join("; ")} }`;
    }
    case "array":
      return `Array<${tsTypeFromSchema(node.items || {})}>`;
    default:
      return primType(node.type);
  }
}

function primType(t) {
  switch (t) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "object":
      return "Record<string, unknown>";
    case "array":
      return "unknown[]";
    default:
      return "unknown";
  }
}

// 스키마의 알려진 경로에서 semantic enum 을 뽑는다(projection DTO 는 안정적 구조).
function factorProps(schema, semanticName) {
  return schema.properties.stocks.items.properties.factors.properties[semanticName].properties;
}

function enumBlock(constName, typeName, values) {
  const arr = values.map((v) => JSON.stringify(v)).join(", ");
  return (
    `export const ${constName} = [${arr}] as const;\n` +
    `export type ${typeName} = (typeof ${constName})[number];\n`
  );
}

function generate() {
  const contractBytes = readBytes(CONTRACT_PATH);
  const schemaBytes = readBytes(PROJECTION_SCHEMA_PATH);
  const contract = JSON.parse(contractBytes.toString("utf8"));
  const schema = JSON.parse(schemaBytes.toString("utf8"));

  const contractHash = sha256(contractBytes);
  const schemaHash = sha256(schemaBytes);

  const lines = [];
  lines.push("// @generated by scripts/gen_metrics251_contracts.mjs — DO NOT EDIT BY HAND.");
  lines.push("// Regenerate: `npm run contract:metrics251` (python export + this generator).");
  lines.push("// Freshness is guarded by `npm run test:metrics251-contracts` (Slice J).");
  lines.push("//");
  lines.push("// Sources (bytes hashed for drift detection):");
  lines.push(`//   config/metrics/2.5.1.contract.json           sha256=${contractHash}`);
  lines.push(`//   config/metrics/2.5.1.projection.schema.json  sha256=${schemaHash}`);
  lines.push("//");
  lines.push("// This file declares CONTRACT TYPES ONLY. It never implements or imports a score");
  lines.push("// formula: Metrics 2.5.1 final scores are computed and sealed by the Python engine");
  lines.push("// and only READ here (docs/ornscore-metrics-v2.5.1-amendment-2026-07-15.md Slice J).");
  lines.push("");
  lines.push(`export const CONTRACT_VERSION = ${JSON.stringify(contract.contractVersion)} as const;`);
  lines.push(`export const ENGINE_VERSION = ${JSON.stringify(contract.engineVersion)} as const;`);
  lines.push("export const CONTRACT_SOURCE_HASHES = {");
  lines.push(`  contractJson: ${JSON.stringify(contractHash)},`);
  lines.push(`  projectionSchema: ${JSON.stringify(schemaHash)},`);
  lines.push("} as const;");
  lines.push("");

  // ---- Python 이 소유한 enum 들 ----
  const e = contract.enums;
  lines.push("// ── Python-owned enums (source: 2.5.1.contract.json) ──────────────────────────");
  lines.push(enumBlock("FACTOR_KEYS", "FactorKey", e.factorKeys));
  lines.push(enumBlock("ELIGIBILITY_REASONS", "EligibilityReason", e.eligibilityReasons));
  lines.push(enumBlock("NON_EXCLUDING_REASONS", "NonExcludingReason", e.nonExcludingReasons));
  lines.push(enumBlock("EXCLUDING_REASONS", "ExcludingReason", e.excludingReasons));
  lines.push(enumBlock("COMPARISON_METRIC_KEYS", "ComparisonMetricKey", e.comparisonMetricKeys));
  lines.push(enumBlock("COMPARISON_REASON_CODES", "ComparisonReasonCode", e.comparisonReasonCodes));
  lines.push(enumBlock("CALENDAR_DAY_KINDS", "CalendarDayKind", e.calendarDayKinds));
  lines.push(enumBlock("READ_STATUSES", "ReadStatus", e.readStatuses));
  lines.push(enumBlock("READ_REASON_CODES", "ReadReasonCode", e.readReasonCodes));
  lines.push(enumBlock("RUN_STATES", "RunState", e.runStates));

  // ---- 필수키·체크섬 메타 계약(런타임 검증에서 재사용) ----
  lines.push("// ── Required-key + checksum-metadata contract (source: 2.5.1.contract.json) ───");
  lines.push(`export const REQUIRED_KEYS = ${JSON.stringify(contract.requiredKeys)} as const;`);
  lines.push(`export const CHECKSUM_METADATA = ${JSON.stringify(contract.checksumMetadata)} as const;`);
  lines.push(`export const ARTIFACT_NAMES = ${JSON.stringify(contract.artifactNames)} as const;`);
  lines.push("");

  // ---- projection DTO 의 semantic enum(스키마 정본) ----
  lines.push("// ── Projection semantic enums (source: 2.5.1.projection.schema.json) ──────────");
  lines.push(
    enumBlock("MOMENTUM_DIRECTIONS", "MomentumDirection", factorProps(schema, "momentum").state.enum)
  );
  lines.push(
    enumBlock("VOLUME_ACTIVITY_STATES", "VolumeActivityState", factorProps(schema, "volumeActivity").state.enum)
  );
  lines.push(enumBlock("VALUE_STATES", "ValueState", factorProps(schema, "value").state.enum));
  lines.push(
    enumBlock("RISK_EFFICIENCY_BANDS", "RiskEfficiencyBand", factorProps(schema, "riskAdjusted").state.enum)
  );
  lines.push(
    enumBlock(
      "RISK_HURDLE_RELATIONS",
      "RiskHurdleRelation",
      factorProps(schema, "riskAdjusted").hurdleRelation.enum
    )
  );
  lines.push(
    enumBlock(
      "COMPOSITE_STATES",
      "CompositeState",
      schema.properties.stocks.items.properties.composite.properties.state.enum
    )
  );
  lines.push(
    enumBlock(
      "VOLUME_ACTIVITY_DENIED_MEANINGS",
      "VolumeActivityDeniedMeaning",
      factorProps(schema, "volumeActivity").deniedMeanings.items.enum
    )
  );
  lines.push(
    enumBlock(
      "RISK_ADJUSTED_DENIED_MEANINGS",
      "RiskAdjustedDeniedMeaning",
      factorProps(schema, "riskAdjusted").deniedMeanings.items.enum
    )
  );

  // ---- projection DTO 전체(스키마에서 재귀 생성) ----
  lines.push("// ── Projection DTO (recursively generated from 2.5.1.projection.schema.json) ──");
  lines.push(`export type Metrics251Projection = ${tsTypeFromSchema(schema)};`);
  lines.push("");

  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");
  const generated = generate();
  const data = Buffer.from(generated, "utf8");

  if (check) {
    if (!existsSync(OUT_PATH)) {
      console.error(`CONTRACT DRIFT: 파일 없음 ${relative(ROOT, OUT_PATH)} — \`npm run contract:metrics251\` 로 생성하세요.`);
      process.exit(1);
    }
    const existing = readBytes(OUT_PATH);
    if (!existing.equals(data)) {
      console.error("CONTRACT DRIFT: scripts/metrics251/contracts.generated.ts 가 소스와 다릅니다.");
      console.error("  → `npm run contract:metrics251` 로 재생성 후 커밋하세요.");
      process.exit(1);
    }
    console.log("generated TS contract: FRESH (소스와 일치)");
    return;
  }

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, data);
  console.log(`generated TS contract: wrote ${relative(ROOT, OUT_PATH)} (${data.length} bytes)`);
}

main();
