// @generated by scripts/gen_metrics251_contracts.mjs — DO NOT EDIT BY HAND.
// Regenerate: `npm run contract:metrics251` (python export + this generator).
// Freshness is guarded by `npm run test:metrics251-contracts` (Slice J).
//
// Sources (bytes hashed for drift detection):
//   config/metrics/2.5.1.contract.json           sha256=9d59bc49b659fb973e5134056c4a2e1a0b0a2ab1bf3aeadbabddbf8dec283381
//   config/metrics/2.5.1.projection.schema.json  sha256=637e3a9fe964687faa1c4da0a3f71dce232a24037d013e59eb2ba30c643b9459
//
// This file declares CONTRACT TYPES ONLY. It never implements or imports a score
// formula: Metrics 2.5.1 final scores are computed and sealed by the Python engine
// and only READ here (docs/ornscore-metrics-v2.5.1-amendment-2026-07-15.md Slice J).

export const CONTRACT_VERSION = "2.5.1" as const;
export const ENGINE_VERSION = "2.5.1" as const;
export const CONTRACT_SOURCE_HASHES = {
  contractJson: "9d59bc49b659fb973e5134056c4a2e1a0b0a2ab1bf3aeadbabddbf8dec283381",
  projectionSchema: "637e3a9fe964687faa1c4da0a3f71dce232a24037d013e59eb2ba30c643b9459",
} as const;

// ── Python-owned enums (source: 2.5.1.contract.json) ──────────────────────────
export const FACTOR_KEYS = ["momentum", "activity", "value", "riskAdjusted"] as const;
export type FactorKey = (typeof FACTOR_KEYS)[number];

export const ELIGIBILITY_REASONS = ["INSUFFICIENT_HISTORY", "MISSING_INPUT", "NON_POSITIVE_FUNDAMENTAL", "QUALITY_WARNING", "SOURCE_DATE_MISMATCH", "SOURCE_DATE_STALE", "VALID", "ZERO_VARIANCE"] as const;
export type EligibilityReason = (typeof ELIGIBILITY_REASONS)[number];

export const NON_EXCLUDING_REASONS = ["QUALITY_WARNING", "VALID"] as const;
export type NonExcludingReason = (typeof NON_EXCLUDING_REASONS)[number];

export const EXCLUDING_REASONS = ["INSUFFICIENT_HISTORY", "MISSING_INPUT", "NON_POSITIVE_FUNDAMENTAL", "SOURCE_DATE_MISMATCH", "SOURCE_DATE_STALE", "ZERO_VARIANCE"] as const;
export type ExcludingReason = (typeof EXCLUDING_REASONS)[number];

export const COMPARISON_METRIC_KEYS = ["momentum", "activity", "value", "riskAdjusted"] as const;
export type ComparisonMetricKey = (typeof COMPARISON_METRIC_KEYS)[number];

export const COMPARISON_REASON_CODES = ["COMPARABLE", "CURRENT_SNAPSHOT_MISSING", "PREVIOUS_SNAPSHOT_MISSING", "CURRENT_UNPUBLISHED", "PREVIOUS_UNPUBLISHED", "ENGINE_VERSION_MISMATCH", "CONFIG_MISMATCH", "SOURCE_CONTRACT_INCOMPATIBLE", "SOURCE_INPUT_UNPUBLISHED", "FACTOR_POPULATION_MISMATCH", "RANKING_UNIVERSE_MISMATCH", "FACTOR_NOT_COMPARABLE", "COMPOSITE_NOT_COMPARABLE"] as const;
export type ComparisonReasonCode = (typeof COMPARISON_REASON_CODES)[number];

export const CALENDAR_DAY_KINDS = ["TRADING_DAY", "WEEKEND", "HOLIDAY", "OUT_OF_CALENDAR_RANGE", "NO_PREVIOUS_MARKET_DAY", "PREVIOUS_MARKET_DATE_MATCH", "PREVIOUS_MARKET_DATE_MISMATCH", "PAIRING_INVALID"] as const;
export type CalendarDayKind = (typeof CALENDAR_DAY_KINDS)[number];

export const READ_STATUSES = ["OK", "UNAVAILABLE", "DEGRADED"] as const;
export type ReadStatus = (typeof READ_STATUSES)[number];

export const READ_REASON_CODES = ["NO_POINTER", "POINTER_UNREADABLE", "POINTER_INVALID", "RUN_MISSING", "MANIFEST_MISSING", "MANIFEST_UNREADABLE", "MANIFEST_HASH_MISMATCH", "POINTER_MANIFEST_MISMATCH", "ARTIFACT_MISSING", "CHECKSUM_MISMATCH", "NOT_SEALED"] as const;
export type ReadReasonCode = (typeof READ_REASON_CODES)[number];

export const RUN_STATES = ["QA_PASSED"] as const;
export type RunState = (typeof RUN_STATES)[number];

// ── Required-key + checksum-metadata contract (source: 2.5.1.contract.json) ───
export const REQUIRED_KEYS = {"factorPopulation":["count","hash"],"factorResult":["factor","reason","raw","score"],"manifest":["snapshotId","marketDate","metricsVersion","runState","artifacts","manifestHash"],"manifestArtifact":["sha256","bytes"],"pointer":["snapshotId","marketDate","metricsVersion","manifestHash","runDir"],"rankingPopulation":["count","hash"],"snapshot":["configHash","eligibilityReasonCounts","engineVersion","factorPopulations","inputManifestHash","marketDate","rankingPopulation","runState","sourceDates","stocks"],"sourceDates":["prices","volumes","fundamentals"],"stockResult":["ticker","factors","compositeScore","rankingEligible","eligibilityReasons"]} as const;
export const CHECKSUM_METADATA = {"artifactChecksumKey":"sha256","manifestHashKey":"manifestHash","pointerManifestHashKey":"manifestHash","populationHashKey":"hash","snapshotHashKeys":["configHash","inputManifestHash"]} as const;
export const ARTIFACT_NAMES = {"manifest":"manifest.json","pointer":"current.json","runsSubdir":"runs","snapshot":"snapshot.json"} as const;

// ── Projection semantic enums (source: 2.5.1.projection.schema.json) ──────────
export const MOMENTUM_DIRECTIONS = ["UP", "FLAT", "DOWN", "UNAVAILABLE"] as const;
export type MomentumDirection = (typeof MOMENTUM_DIRECTIONS)[number];

export const VOLUME_ACTIVITY_STATES = ["VERY_LOW", "DECREASED", "NORMAL", "INCREASED", "SIGNIFICANT_INCREASE", "SURGE", "UNAVAILABLE"] as const;
export type VolumeActivityState = (typeof VOLUME_ACTIVITY_STATES)[number];

export const VALUE_STATES = ["PRESENT", "UNAVAILABLE"] as const;
export type ValueState = (typeof VALUE_STATES)[number];

export const RISK_EFFICIENCY_BANDS = ["LOW", "NEUTRAL", "HIGH", "UNAVAILABLE"] as const;
export type RiskEfficiencyBand = (typeof RISK_EFFICIENCY_BANDS)[number];

export const RISK_HURDLE_RELATIONS = ["ABOVE", "AT", "BELOW", "UNAVAILABLE"] as const;
export type RiskHurdleRelation = (typeof RISK_HURDLE_RELATIONS)[number];

export const COMPOSITE_STATES = ["ELIGIBLE", "WITHHELD"] as const;
export type CompositeState = (typeof COMPOSITE_STATES)[number];

export const VOLUME_ACTIVITY_DENIED_MEANINGS = ["priceDirection", "buyerIdentity", "liquidity", "fundInflow", "buyingPressure"] as const;
export type VolumeActivityDeniedMeaning = (typeof VOLUME_ACTIVITY_DENIED_MEANINGS)[number];

export const RISK_ADJUSTED_DENIED_MEANINGS = ["latestRiskFreeRate", "safetyGuarantee", "futureReturn"] as const;
export type RiskAdjustedDeniedMeaning = (typeof RISK_ADJUSTED_DENIED_MEANINGS)[number];

// ── Projection DTO (recursively generated from 2.5.1.projection.schema.json) ──
export type Metrics251Projection = { "projectionVersion": "2.5.1"; "engineVersion": "2.5.1"; "configHash": string; "copyVersion": "2.5.1"; "marketDate": string; "sourceDates": { "prices": string | null; "volumes": string | null; "fundamentals": string | null }; "hurdleRate": number; "stocks": Array<{ "ticker": string; "composite": { "state": "ELIGIBLE" | "WITHHELD"; "copyKey": string; "rankingEligible": boolean; "sourceCompositeScore": number | null }; "factors": { "momentum": { "factor": "momentum"; "semanticName": "momentum"; "state": "UP" | "FLAT" | "DOWN" | "UNAVAILABLE"; "copyKey": string; "sourceRaw": number | null; "sourceScore": number | null; "sourceReason": string }; "volumeActivity": { "factor": "activity"; "semanticName": "volumeActivity"; "state": "VERY_LOW" | "DECREASED" | "NORMAL" | "INCREASED" | "SIGNIFICANT_INCREASE" | "SURGE" | "UNAVAILABLE"; "copyKey": string; "deniedMeanings": Array<"priceDirection" | "buyerIdentity" | "liquidity" | "fundInflow" | "buyingPressure">; "sourceRaw": number | null; "sourceScore": number | null; "sourceReason": string }; "value": { "factor": "value"; "semanticName": "value"; "state": "PRESENT" | "UNAVAILABLE"; "copyKey": string; "sourceScore": number | null; "sourceReason": string }; "riskAdjusted": { "factor": "riskAdjusted"; "semanticName": "riskAdjusted"; "state": "LOW" | "NEUTRAL" | "HIGH" | "UNAVAILABLE"; "copyKey": string; "hurdleRelation": "ABOVE" | "AT" | "BELOW" | "UNAVAILABLE"; "hurdleRelationCopyKey": string; "hurdleRate": number; "deniedMeanings": Array<"latestRiskFreeRate" | "safetyGuarantee" | "futureReturn">; "sourceRaw": number | null; "sourceScore": number | null; "sourceReason": string } } }> };
